#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------
encoding: utf-8

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Overall title for pages.
title: "Cloud 101 For AWS"

# Repository URL (without trailing slash).
repo: https://github.com/uwescience/hsistem-cloud101

# Root URL below username.github.io domain, with leading slash but no trailing slash.
# For example, for 'https://geohackweek.github.io/lesson-example', use '/lesson-example'.
root: "/hsistem-cloud101"

# Contact email address.
email: amandach@uw.edu

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Is this production or development? (Overridden in _config_dev.yml.)
is_production: true

# Sites.
ghw_site: "https://amanda-tan.github.io"
ghw_github: "https://github.com/amanda-tan"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/swcarpentry/styles"
example_repo: "https://github.com/swcarpentry/lesson-example"
example_site: "https://swcarpentry.github.com/lesson-example"

# Start time in minutes (540 is 09:00 am)
start_time: 615

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn off built-in syntax highlighting.
highlighter: false
